export const dataList = {
  Movie: [
      {
          _Number: "2148",
          _Checked: "True",
          _ColorTag: "0",
          _Date: "2023-12-22",
          _Rating: "8.9",
          _OriginalTitle: "Le Mani sulla citta",
          _TranslatedTitle: "Main basse sur la ville",
          _FormattedTitle: "Le Mani sulla citta (Main basse sur la ville)",
          _Director: "Francesco Rosi",
          _Producer: "Lionello Santi",
          _Writer: "Francesco Rosi, Raffaele La Capria, Enzo Forcella",
          _Composer: "Piero Piccioni",
          _Actors: "Rod Steiger (Edoardo Nottola), Salvo Randone (Professor De Angelis), Guido Alberti (Maglione), Marcello Cannavale (Friend of Nottola), Dante Pinto (President of Inquiry Committee), Alberto Conocchia (Friend of Nottola), Carlo Fermariello (De Vita), Terenzio Cordova (Prosecutor), Angelo D'Alessandro (Balsamo), Vincenzo Metafora (Mayor), Dany Paris (Dany), Renato Terra (Reporter), Alberto Amato (), Mario Perelli ()",
          _Country: "Italie, France",
          _Year: "1963",
          _Length: "101",
          _Category: "Drame",
          _URL: "https://www.allocine.fr/film/fichefilm_gen_cfilm=4300.html",
          _Description: "Poussee par l'entrepreneur Nottola, la municipalite de Naples utilise des terrains agricoles pour lancer le construction d'un gigantesque programme immobilier. Les speculateurs en profitent, mais la proximite du chantier provoque l'ecroulement d'une maison ancienne et la mort d'un enfant, ce qui declenche de vives polemiques au sein du conseil municipal, alors que de nouvelles elections se preparent. Tandis que l'enquete sur l'accident s'enlise, les strategies electorales s'affinent...",
          _Comments: "Date de sortie cinema : 7 novembre 1963 en salle||Note de la presse : 5,0/5|Note des spectateurs : 3,9/5 (Pour  notes)||Bande Annonce : https://www.allocine.fr/_video/iblogvision.aspx?cmedia=19598465||Fiche Technique :|- Nationalites : Italie, France |- Distributeur Les Acacias |- Recompense # prix |- Annee de production : 1963 |- Date de sortie DVD : 24/10/2006 |- Date de sortie Blu-ray : 22/11/2023 |- Date de sortie VOD : 01/02/2016 |- Type de film : Long-metrage |- Secrets de tournage 5 anecdotes |- Budget : - |- Date de reprise 16/11/2022 |- Langues : Italien |- Format production : - |- Couleur : N&B |- Format audio : - |- Format de projection : - |- Ne de Visa : 28104||Secrets de tournage :||Venise|Main basse sur la ville a remporte le Lion d'Or e la Mostra de Venise de 1963.||Retrouvailles tardives|En 1973, soit dix ans apres avoir tourne Main basse sur la ville, le realisateur Francesco Rosi retrouvera l'acteur Rod Steiger pour le rele de Gene Giannini dans Lucky Luciano.||Duo gagnant|Main basse sur la ville marque la premiere collaboration scenaristique entre Francesco Rosi et le scenariste Raffaele La Capria. Par la suite, ils signent tous les deux les scenarios de La Belle et le cavalier (1967), Les Hommes contre (1970) et celui de Le Christ s'est arrete e Eboli (1979), tous realises par Rosi.||Premier rele|Lors de leurs recherches pour le film, Francesco Rosi et Raffaele La Capria ont assiste e de vrais conseils municipaux afin de restituer au mieux la realite. Ainsi, l'interpretation de De Vita marque le premier e et dernier - rele au cinema pour Carlo Fermariello, veritable conseiller municipal communiste dans la vie.||Trente ans plus tard...|Trente ans apres la sortie de Main basse sur la ville, Francesco Rosi, toujours avec la participation de son complice Raffaele La Capria, realisa un documentaire sur la ville de Naples, e l'occasion de la projection du film dans une universite d'architecture. Rosi filme le debat qui suit, oe des politiques, universitaires, etudiants et artistes donnent leur point de vue sur la ville, sur ce qui a change ou non en trente ans...",
          _FilePath: "U:\\Films\\Main basse sur la ville 1h38 TNTHDfrast.ts",
          _VideoFormat: "AVC",
          _VideoBitrate: "4935",
          _AudioFormat: "MPEG-1 Audio layer 2, 2.0",
          _AudioBitrate: "192",
          _Resolution: "1920x1080",
          _Framerate: "25,000",
          _Languages: "French",
          _Subtitles: "French, French",
          _Size: "3786",
          _Disks: "1",
          _Picture: "Films_2148.jpg"
      },
      {
          _Number: "2149",
          _Checked: "True",
          _ColorTag: "0",
          _Date: "2023-12-22",
          _Rating: "4.8",
          _OriginalTitle: "Marseille",
          _TranslatedTitle: "Marseille",
          _FormattedTitle: "Marseille (Marseille)",
          _Director: "Kad Merad",
          _Producer: "Richard Grandpierre, Cyril Colbeau-Justin, Jean-Baptiste Dupont",
          _Writer: "Kad Merad, Patrick Bosso, Judith El Zein",
          _Composer: "Herve Rakotofiringa",
          _Actors: "Kad Merad (Paolo), Patrick Bosso (Joseph), Venantino Venantini (Giovanni), Judith El Zein (Elena), Anne Charrier (Valerie), Julien Boisselier (Pierre), Louis-Do de Lencquesaing (Stephane), Philippe Lefebvre (Le Directeur du CTC), Mathieu Madenian (Le Maetre d'hetel du Petit Nice), Eric Fraticelli (), Sophie Garagnon (Infirmiere CTC)",
          _Country: "France",
          _Year: "2015",
          _Length: "102",
          _Category: "Comedie, Drame",
          _URL: "https://www.allocine.fr/film/fichefilm_gen_cfilm=232393.html",
          _Description: "Devant l'insistance de son frere Joseph, qu'il n'a pas revu depuis 25 ans, Paolo se resout e abandonner quelques jours sa vie calme et harmonieuse au Canada, pour revenir e Marseille au chevet de son pere accidente. Il part donc, son fils sous le bras, bien decide e ne pas s'attarder dans cette ville qu'il a fui, des annees plus tet, e la suite d'un drame. Il n'imagine pas que l'affection de sa famille retrouvee, sa rencontre amoureuse avec une jeune femme et la solidarite joyeuse et simple des Marseillais le reconcilieront avec cette ville qu'il n'aurait jamais voulu quitter... Marseille.|||",
          _FilePath: "U:\\Films\\Marseille 1h35 TNTHDfrast.ts",
          _VideoFormat: "AVC",
          _VideoBitrate: "3695",
          _AudioFormat: "AC3+, 2.0",
          _AudioBitrate: "128",
          _Resolution: "1920x1080",
          _Framerate: "25,000",
          _Languages: "French",
          _Subtitles: "French",
          _Size: "2741",
          _Disks: "1",
          _Picture: "Films_2149.jpg"
      },
      {
          _Number: "2150",
          _Checked: "True",
          _ColorTag: "0",
          _Date: "2023-12-22",
          _Rating: "6.8",
          _OriginalTitle: "No Time To Die",
          _TranslatedTitle: "Mourir peut attendre",
          _FormattedTitle: "No Time To Die (Mourir peut attendre)",
          _Director: "Cary Joji Fukunaga",
          _Producer: "Barbara Broccoli, Michael G. Wilson",
          _Writer: "Neal Purvis, Robert Wade, Cary Joji Fukunaga, Phoebe Waller-Bridge",
          _Composer: "Hans Zimmer",
          _Actors: "Daniel Craig (James Bond), Lea Seydoux (Madeleine Swann), Rami Malek (Lyutsifer Safin), Christoph Waltz (Ernst Stavro Blofeld), Ana de Armas (Paloma), Ralph Fiennes (M), Naomie Harris (Eve Moneypenny), Lashana Lynch (Nomi), Ben Whishaw (Q), Jeffrey Wright (Felix Leiter), Billy Magnussen (Logan Ash), David Dencik (Valdo Obruchev), Rory Kinnear (Bill Tanner), Dali Benssalah (Primo), Lisa-Dorah Sonnet (Mathilde), Coline Defaud (), Mathilde Bourbin (), Hugh Dennis (Dr. Hardy), Priyanga Burford (Dr. Symes), Pio Amato (), Gediminas Adomaitis (), Brigitte Millar (Vogel), Amy Morgan (Alison Smith), Lizzie Winkler (Sarah Jones), Andrei Nova (Un garde du bunker), Andy Cheung (II) (), Hayden Phillips (Sir Sebastian Death), Joe Grossi (), Javone Prince (), Rae Lim (Spectre Agent), Lourdes Faberes (Spectre Agent), Steve Barnett (II) (Spectre Agent (SA09)), Tuncay Gunes (Spectre Agent), Clem So (Spectre Agent), Denis Khoroshko (Spectre Agent), Philip Philmar (Spectre Agent), Raymond Waring (Spectre Agent), Eliot Sumner (Bodyguard), Rod Hunt (Spectre Bodyguard), Gordon Alexander (Lab Technician)",
          _Country: "U.S.A., Grande-Bretagne",
          _Year: "2021",
          _Length: "163",
          _Category: "Action, Thriller, Espionnage",
          _URL: "https://www.allocine.fr/film/fichefilm_gen_cfilm=212358.html",
          _Description: "Dans MOURIR PEUT ATTENDRE, Bond a quitte les services secrets et coule des jours heureux en Jamaeque. Mais sa tranquillite est de courte duree car son vieil ami Felix Leiter de la CIA debarque pour solliciter son aide : il s'agit de sauver un scientifique qui vient d'etre kidnappe. Mais la mission se revele bien plus dangereuse que prevu et Bond se retrouve aux trousses d'un mysterieux ennemi detenant de redoutables armes technologiquese",
          _FilePath: "U:\\Films\\Mourir peut attendre 2h32 TNTHDfraengst.ts",
          _VideoFormat: "AVC",
          _VideoBitrate: "5111",
          _AudioFormat: "AC3+, AC3+, 2.0, 2.0",
          _AudioBitrate: "128",
          _Resolution: "1920x1080",
          _Framerate: "25,000",
          _Languages: "French, qaa",
          _Subtitles: "French, French",
          _Size: "6156",
          _Disks: "1",
          _Picture: "Films_2150.jpg"
      },
      {
          _Number: "2151",
          _Checked: "True",
          _ColorTag: "0",
          _Date: "2023-12-22",
          _Rating: "4.2",
          _OriginalTitle: "Passenger 57",
          _TranslatedTitle: "Passager 57",
          _FormattedTitle: "Passenger 57 (Passager 57)",
          _Director: "Kevin Hooks",
          _Producer: "Dan Paulson, Lee Rich, Dylan Sellers",
          _Writer: "David Loughery, Dan Gordon",
          _Composer: "Stanley Clarke",
          _Actors: "Wesley Snipes (John Cutter), Bruce Payne (Charles Rane), Tom Sizemore (Sly Delvecchio), Alex Datcher (Marti Slayton), Elizabeth Hurley (Sabrina Ritchie), Bruce Greenwood (Stuart Ramsey), Robert Hooks (Dwight Henderson), Michael Horse (Forget), Marc Macaulay (Vincent), Ernie Lively (Chief Biggs), Joel Fogel (Dr. Bauman), Jane McPherson (Nurse)",
          _Country: "U.S.A.",
          _Year: "1992",
          _Length: "86",
          _Category: "Action, Thriller",
          _URL: "https://www.allocine.fr/film/fichefilm_gen_cfilm=31002.html",
          _Description: "Un dangereux terroriste s'est echappe du centre de detention oe il etait retenu, en utilisant la ruse. Celui-ci detourne peu apres un avion, mais en ignorant que se trouve e bord un expert de la securite : John Cutter.",
          _Comments: "Date de sortie cinema : 12 mai 1993 en salle||Note des spectateurs : 2,1/5 (Pour  notes)||Bande Annonce : https://www.allocine.fr/_video/iblogvision.aspx?cmedia=19371873||Fiche Technique :|- Nationalite : U.S.A. |- Distributeur : - |- Annee de production : 1992 |- Date de sortie DVD : - |- Date de sortie Blu-ray : 04/09/2013 |- Date de sortie VOD : 14/03/2009 |- Type de film : Long-metrage |- Secrets de tournage : - |- Budget : 15 000 000 $ |- Langues : Anglais |- Format production : - |- Couleur : Couleur |- Format audio : - |- Format de projection : - |- Ne de Visa : 81777",
          _FilePath: "U:\\Films\\Passager 57 1h17 TNTHDfraengst.ts",
          _VideoFormat: "AVC",
          _VideoBitrate: "4371",
          _AudioFormat: "AC3+, AC3+, 2.0, 2.0",
          _AudioBitrate: "160",
          _Resolution: "1920x1080",
          _Framerate: "25,000",
          _Languages: "French, qaa",
          _Subtitles: "French",
          _Size: "2732",
          _Disks: "1",
          _Picture: "Films_2151.jpg"
      },
      {
          _Number: "2152",
          _Checked: "True",
          _ColorTag: "0",
          _Date: "2023-12-22",
          _Rating: "5.6",
          _OriginalTitle: "Tacones lejanos",
          _TranslatedTitle: "Talons Aiguilles",
          _FormattedTitle: "Tacones lejanos (Talons Aiguilles)",
          _Director: "Pedro Almodevar",
          _Writer: "Pedro Almodevar",
          _Composer: "Ryuichi Sakamoto",
          _Actors: "Victoria Abril (Rebeca Giner), Marisa Paredes (Becky del Paramo), Miguel Bose (Juez Domenguez / Hugo), Anna Lizaran (Margarita), Feodor Atkine (Manuel Giner), Cristina Marcos (Paula), Pedro Deez del Corral (Alberto), Bibiana Fernendez (Susana), Nacho Martinez (Juan), Miriam Diaz-Aroca (Isabel), Javier Bardem (Regidor T.V.), Lupe Barrado (Luisa), Mayrata O'Wisiedo (Madre del Juez Domenguez), Juan Jose Otegui (Capellen Hospital), Paula Soldevila (Enfermera Hospital), Gabriel Garbisu (Realizador T.V.), Eva Siva (Tata), Angelina Llongueras (Funcionaria 1), Carmen Navarro (Funcionaria 2), Agusten Almodevar (Cliente tienda de fotos), Roxy Vaz (Dealer), Montse G. Romeu (Maquilladora 1), Lina Mira (Maquilladora 2), Abraham Garcea (Medico Carcel), Rodolfo Montero (Policea T.V.), Jose Marea Sacristen (Sacerdote), Hilario Pino (Locutor), Marea Pau Domenguez (Locutora), Fernando Prados (Agente Judicial), Placido Guimaraes (Negro Isla Margarita)",
          _Country: "Espagne, France",
          _Year: "1991",
          _Length: "113",
          _Category: "Comedie dramatique, Romance",
          _URL: "https://www.allocine.fr/film/fichefilm_gen_cfilm=1992.html",
          _Description: "Apres des annees deabsence, Becky Del Paramo, celebre chanteuse pop des annees soixante, rentre e Madrid. Ceest pour trouver sa fille, Rebecca, mariee e un de ses anciens amants, Manuel. Becky comprend vite que le mariage de Rebecca est un naufrage surtout quand Manuel lui propose de reprendre leur ancienne relation. Une nuit, Manuel est assassine",
          _FilePath: "U:\\Films\\Talons aiguilles 1h51 TNTHDfraespst.ts",
          _VideoFormat: "AVC",
          _VideoBitrate: "5023",
          _AudioFormat: "AC3+, AC3+, 2.0, 2.0",
          _AudioBitrate: "128",
          _Resolution: "1920x1080",
          _Framerate: "25,000",
          _Languages: "French, qaa",
          _Subtitles: "French, French",
          _Size: "4439",
          _Disks: "1",
          _Picture: "Films_2152.jpg"
      }
  ]
};

